.TH ecryptfs-zombie-kill 1 2008-07-21 ecryptfs-utils "eCryptfs"
.SH NOM
ecryptfs-zombie-kill \- tue un zombie eCryptfs.

.SH SYNOPSIS
\fBecryptfs-zombie-kill\fP

.SH DESCRIPTION
\fBecryptfs-zombie-kill\fP est un utilitaire pour tuer un zombie eCryptfs qui peut être créer par identification PAM et insertion de clef dans le noyau.

.SH VOIR AUSSI
.PD 0
.TP
\fBecryptfs\fP(7), \fBecryptfs-zombie-list\fP(1), \fBkeyctl\fP(1), \fBpam_ecryptfs\fP(8)

.TP
\fI/usr/share/doc/ecryptfs-utils/ecryptfs-faq.html\fP

.TP
\fIhttp://ecryptfs.sourceforge.net/\fP
.PD

.SH AUTEUR
Cette page de manuel a été écrite par Dustin Kirkland <kirkland@canonical.com> pour les systèmes Ubuntu (mais peut-être utilisés our d'autres systèmes).  Traduction par James Dupin <james@dupin.info>. Permission est donnée de copier, distribuer et/ou modifier ce document dans les termes de la licence publique générale GNU (GNU General Public License), version 2 ou toute autre version plus récente publiée par la Free Software Foundation.

Dans les systèmes Debian, le texte complet de la licence publique générale GNU (GNU General Public License) se trouve dans /usr/share/common-licenses/GPL.
