.TH ecryptfs-mount-private 1 2008-07-21 ecryptfs-utils "eCryptfs"
.SH NOM
ecryptfs-mount-private \- ensemble de scripts (wrapper script) de montage eCryptfs.

.SH SYNOPSIS
\fBecryptfs-mount-private\fP

.SH DESCRIPTION
\fBecryptfs-mount-private\fP est un ensemble de scripts pour l'utilitaire \fBmount.ecryptfs_private\fP.  Le montage est effectué si ~/.ecryptfs/auto-mount existe et vérification est faite que ~/.Private a les permissions 500 et que ~/Private a les permissions 700.

.SH FICHIERS
\fI~/.ecryptfs/auto-mount\fP - \fBecryptfs-mount-private\fP ne s'exécutera que si ce fichier existe

\fI~/.Private\fP - répertoire sous-jacent contenant les données chiffrées

\fI~/Private\fP - point de montage contenant les données déchiffrées (losrque le montage a été effectué)

\fI~/.ecryptfs/Private.sig\fP - fichier contenant la signature de la clef du point de montage

.SH "EXEMPLES"
.nf
.B Pour accéder à vos données cryptées depuis un livecd
.fi
Pour utilisateur ayant pour identifiant user, mot de passe password et dont le répertoire /home/user crypté est dans la partition racine / se trouvant dans /dev/sda1
sudo mount /dev/sda1 /mnt
sudo mount -o bind /dev /mnt/dev
sudo mount -o bind /proc /mnt/proc
sudo mount -o bind /sys /mnt/sys
sudo chroot /mnt
su - user
ecryptfs-mount-private
cd

.SH VOIR AUSSI
.PD 0
.TP
\fBmount.ecryptfs_private\fP(1), \fBecryptfs-umount-private\fP(1)

.TP
\fI/usr/share/doc/ecryptfs-utils/ecryptfs-faq.html\fP

.TP
\fIhttp://ecryptfs.sourceforge.net/\fP
.PD

.SH AUTEUR
Cette page de manuel a été écrite par Dustin Kirkland <kirkland@canonical.com> pour les systèmes Ubuntu (mais peut-être utilisés our d'autres systèmes).  Traduction par James Dupin <james@dupin.info>. Permission est donnée de copier, distribuer et/ou modifier ce document dans les termes de la licence publique générale GNU (GNU General Public License), version 2 ou toute autre version plus récente publiée par la Free Software Foundation.

Dans les systèmes Debian, le texte complet de la licence publique générale GNU (GNU General Public License) se trouve dans /usr/share/common-licenses/GPL.

