#!/bin/sh -e
# This script unmounts a user's private ecryptfs folder
#
# Original by Michael Halcrow, IBM
# Extracted to a stand-alone script by Dustin Kirkland <kirkland@canonical.com>

/sbin/umount.ecryptfs_private
