#!/bin/sh -e
#
#    ecryptfs-rewrite-file
#    Copyright (C) 2008 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 2 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

error() {
	echo "[FAILED]"
	echo "ERROR: $1" 1>&2
}
j=0
OKs=0
for i in "$@"; do
	j=`expr $j + 1`
	echo -n "INFO: Rewriting [$j/$#] [$i] ... "
	if [ ! -e "$i" ] ; then
		error "File does not exists"
		continue
	fi
	if [ "$i" = "." ]; then
		echo "[EXCLUDED]" >&2
		continue
	fi
	opt=
	if [ -d "$i" -a ! -h "$i" ]; then
		# A directory, re-encrypt the filename
		temp1=`mktemp -d "$i".XXXXXXXXXX` || {
			error "Could not create tempdir"
			continue
		}
		mv -f -T "$i" "$temp1" 2>/dev/null  || {
			error "Could not rename [$i] to [$temp1]"
			rmdir "$temp1"
			continue
		}
		mv -f "$temp1" "$i" 2>/dev/null || {
			error "Could not rename [$temp1] to [$i]"
		}
	else
		# A file or symlink, re-encrypt the contents
		temp1=`mktemp "$i".XXXXXXXXXX` || {
			error "Could not create tempfile"
			continue
		}
		cp -a "$i" "$temp1" 2>/dev/null || {
			error "Could not copy [$i] to [$temp1]"
			rm -f "$temp1"
			continue
		}
		mv -f "$temp1" "$i" 2>/dev/null || {
			error "Could not rename [$temp1] to [$i]"
			continue
		}
	fi
	echo "[OK]"
	OKs=$((OKs+1))
done
echo "$OKs/$j rewrites succeeded"
[ $OKs -ne $j ] && exit 1
exit 0
