#!/bin/sh -e
#
#    ecryptfs-rewrite-file
#    Copyright (C) 2008 Canonical Ltd.
#
#    Authors: Dustin Kirkland <kirkland@canonical.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 2 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

error() {
	echo "ERROR: $1" 1>&2
	exit 1
}
for i in "$@"; do
	[ "$i" = "." ] && continue
	opt=
	[ -d "$i" -a ! -h "$i" ] && opt="-d"
	temp1=`mktemp $opt "$i".XXXXXXXXXX` || error "Could not create tempfile"
	mv -f -T "$i" "$temp1"	|| error "Could not rename [$i] to [$temp1]"
	mv -f "$temp1" "$i"	|| error "Could not rename [$temp1] to [$i]"
done
exit 0
