#!/bin/sh -e
#    ecryptfs-record-passphrase
#    Copyright (C) 2012 Dustin Kirkland <dustin.kirkland@gmail.com>
#
#    Authors: Dustin Kirkland <dustin.kirkland@gmail.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; version 2 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.

msg="
Usually your encrypted directory is unlocked automatically with your LOGIN
password.  But if you ever need to manually recover your encrypted data
manually, you must have your randomly generated MOUNT passphrase.

YOU MUST RECORD THIS MOUNT PASSPHRASE AND STORE IT SOMEWHERE SAFE!

You can:
 (1) Enter your LOGIN password, display and manually write down your
     randomly generated MOUNT passphrase
 (2) Backup your randomly generated MOUNT passphrase to KeyEscrow.net
     (or compatible) key escrow service in the Cloud.

Enter your choice [1-2]: "

while true; do
	echo -n "$msg"
	choice=$(head -n1)
	case "$choice" in
		1)
			exec ecryptfs-unwrap-passphrase "$HOME/.ecryptfs/wrapped-passphrase"
		;;
		2)
			exec ecryptfs-escrow-private
		;;
	esac
done
