.TH ecryptfs-mount-private 1 2008-11-13 ecryptfs-utils "eCryptfs"
.SH NAME
ecryptfs-mount-private \- interactive eCryptfs private mount wrapper script.

.SH SYNOPSIS
\fBecryptfs-mount-private\fP

.SH DESCRIPTION
\fBecryptfs-mount-private\fP is a wrapper script for the \fBmount.ecryptfs_private\fP utility that will interactively prompt for the user's login password, if necessary.

.SH FILES
\fI~/.Private\fP - underlying directory containing encrypted data

\fI~/Private\fP - mountpoint containing decrypted data (when mounted)

\fI~/.ecryptfs/Private.sig\fP - file containing signature of mountpoint passphrase

\fI~/.ecryptfs/wrapped-passphrase\fP - file containing the wrapped passphrase

\fI~/.ecryptfs/wrapping-independent\fP - this file exists if the wrapping passphrase is independent from login passphrase

.SH SEE ALSO
.PD 0
.TP
\fBmount.ecryptfs_private\fP(1), \fBecryptfs-umount-private\fP(1)

.TP
\fI/usr/share/doc/ecryptfs-utils/ecryptfs-faq.html\fP

.TP
\fIhttp://ecryptfs.org/\fP
.PD

.SH AUTHOR
This manpage and the \fBecryptfs-mount-private\fP utility was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.

On Debian and Ubuntu systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
