.TH ecryptfs-rewrap-passphrase 1 2008-07-21 ecryptfs-utils "eCryptfs"
.SH NAME
ecryptfs-rewrap-passphrase \- unwrap an eCryptfs wrapped passphrase, rewrap it with a new passphrase, and write it back to file.

.SH SYNOPSIS
\fBecryptfs-rewrap-passphrase [file]\fP

printf "%s\\n%s" "old wrapping passphrase" "new wrapping passphrase" | \fBecryptfs-rewrap-passphrase [file] -\fP

.SH DESCRIPTION
\fBecryptfs-rewrap-passphrase\fP is a utility to change the wrapping passphrase on a wrapped passphrase file.

.SH SEE ALSO
.PD 0
.TP
\fBecryptfs\fP(7), \fBecryptfs-unwrap-passphrase\fP(1), \fBecryptfs-wrap-passphrase\fP(1)

.TP
\fI/usr/share/doc/ecryptfs-utils/ecryptfs-faq.html\fP

.TP
\fIhttp://ecryptfs.org/\fP
.PD

.SH AUTHOR
This manpage was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.

On Debian and Ubuntu systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
