.TH ecryptfs-wrap-passphrase 1 2008-07-21 ecryptfs-utils "eCryptfs"
.SH NAME
ecryptfs-wrap-passphrase \- wrap an eCryptfs mount passphrase.

.SH SYNOPSIS
\fBecryptfs-wrap-passphrase [file]\fP

printf "%s\\n%s" "passphrase to wrap" "wrapping passphrase" | \fBecryptfs-wrap-passphrase [file] -\fP

.SH DESCRIPTION
\fBecryptfs-wrap-passphrase\fP is a utility to wrap an eCryptfs mount passphrase, using a specified wrapping passphrase, and write the encrypted output to file.

.SH SEE ALSO
.PD 0
.TP
\fBecryptfs\fP(7), \fBecryptfs-rewrap-passphrase\fP(1), \fBecryptfs-unwrap-passphrase\fP(1)

.TP
\fI/usr/share/doc/ecryptfs-utils/ecryptfs-faq.html\fP

.TP
\fIhttp://ecryptfs.org/\fP
.PD

.SH AUTHOR
This manpage was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.

On Debian and Ubuntu systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
