.TH ecryptfs-remove-private 1 2008-11-17 ecryptfs-utils "eCryptfs"
.SH NAME
ecryptfs-remove-private \- display instructions on how to remove your private directory setup

.SH SYNOPSIS
\fBecryptfs-remove-private\fP

.SH DESCRIPTION
This script WILL NOT actually remove any data, as this is should be a very personal, conscious operation.

Rather, this script will display instructions on how to break down your encrypted private setup.

.SH AUTHOR
This manpage and the \fBecryptfs-remove-private\fP utility was written by Dustin Kirkland <kirkland@canonical.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.

On Debian systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
