.TH ecryptfs-add-passphrase 1 2008-07-21 ecryptfs-utils "eCryptfs"
.SH NAME
ecryptfs-add-passphrase \- add an eCryptfs mount passphrase to the kernel keyring.

.SH SYNOPSIS
\fBecryptfs-add-passphrase\fP [\-\-fnek]

printf "%s" "passphrase" | \fBecryptfs-add-passphrase\fP [\-\-fnek] -

.SH DESCRIPTION
\fBecryptfs-add-passphrase\fP is a utility to manually add a passphrase to the kernel keyring.

If the \-\-fnek option is specified, the filename encryption key associated with the input passphrase will also be added to the keyring.

.SH SEE ALSO
.PD 0
.TP
\fBecryptfs\fP(7), \fBkeyctl\fP(1)

.TP
\fI/usr/share/doc/ecryptfs-utils/ecryptfs-faq.html\fP

.TP
\fIhttp://ecryptfs.org/\fP

.PD

.SH AUTHOR
This manpage was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.

On Debian and Ubuntu systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
