.TH mount.ecryptfs 8 "May 2007" ecryptfs-utils "eCryptfs"
.SH NAME
mount.ecryptfs \- eCryptfs mount helper.

.SH SYNOPSIS
\fBmount \-t ecryptfs\fP [\fIlower\ directory\fP] [\fIecryptfs\ mount\ point\fP]

.SH DESCRIPTION
\fBmount.ecryptfs\fP is eCryptfs mount helper. The mount utility will defer to the mount helper to perform various configuration tasks; use the -i option to bypass the mount helper if you would rather manually specify your mount options. To mount eCryptfs, specify the lower directory (i.e., /root/crypt) for the encrypted files and the eCryptfs mountpoint (i.e., /mnt/crypt) for the decrypted view of the files:

\fImount \-t ecryptfs /root/crypt /mnt/crypt\fP

.SH "SEE ALSO"
.PD 0
.TP
\fBecryptfs\fP(7), \fBecryptfsd\fP(8), \fBecryptfs-manager\fP(8), \fBmount\fP(8)

.TP
\fI/usr/share/doc/ecryptfs-utils/ecryptfs-faq.html\fP

.TP
\fIhttp://ecryptfs.org/\fP
.PD

.SH AUTHOR
This manpage was written by William Lima <wlima.amadeus@gmail.com> for the Ubuntu system (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.

On Debian and Ubuntu systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
