.TH umount.ecryptfs 8 2009-08-17 ecryptfs-utils "eCryptfs"
.SH NAME
umount.ecryptfs \- eCryptfs umount helper.

.SH SYNOPSIS
\fBumount\fP [\fIecryptfs\ mount\ point\fP]

.SH DESCRIPTION
\fBumount.ecryptfs\fP is an eCryptfs umount helper, that will also unlink keys from the keyring.

.SH "SEE ALSO"
.PD 0
.TP
\fBmount.ecryptfs\fP(8), \fBmount\fP(8)

.TP
\fIhttp://ecryptfs.org/\fP
.PD

.SH AUTHOR
This manpage was written by Dustin Kirkland <kirkland@ubuntu.com> for Ubuntu systems (but may be used by others).  Permission is granted to copy, distribute and/or modify this document under the terms of the GNU General Public License, Version 2 or any later version published by the Free Software Foundation.

On Debian and Ubuntu systems, the complete text of the GNU General Public License can be found in /usr/share/common-licenses/GPL.
